In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 

from Funciones_Datos_EDA import *

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('proyecto_viviendas.csv')
df.head()

,Unnamed: 0,Títulos,Ubicaciones,Precios,Número de habitaciones,Número de baños,Medidas,Equipamientos,Características,Consumo energético,Descripciones,Fechas de publicación
0,0,Piso en venta en Pacífico de 5 habitaciones co...,"Pacífico, Retiro, Madrid",565.000 €,5.0,2.0,160 m²,"['Armarios empotrados', 'Ascensor', 'Balcón', ...","['Combustible calefacción: gas natural', 'Esta...","['Consumo', 'e']",Acacia Wellness ofrece en VENTA:\n\nPiso de 16...,25/10/2023
1,1,Piso en venta en Justicia - Chueca de 1 habita...,"Justicia - Chueca, Centro, Madrid",299.990 €,1.0,1.0,84 m²,NaN,"['Estado: buen estado', 'Interior / exterior: ...",NaN,Vivienda2 te ofrece la oportunidad de adquirir...,22/11/2023
2,2,Venta de piso en Embajadores - Lavapiés de 1 h...,"Embajadores - Lavapiés, Centro, Madrid",179.000 €,1.0,1.0,57 m²,NaN,"['Estado: buen estado', 'Interior / exterior: ...",NaN,Vivienda2 vende local habilitado como apartame...,05/12/2023
3,3,Venta de piso en Canillas de 4 habitaciones co...,"Canillas, Hortaleza, Madrid",1.875.000 €,4.0,5.0,346 m²,"['Aire acondicionado', 'Armarios empotrados', ...","['Aire acondicionado: otros', 'Año de construc...","['Consumo', 'Emisiones', 'a']",Se vende fantastica vivienda arrendada con inq...,03/03/2023
4,4,Venta de piso en Piovera - Conde Orgaz de 4 ha...,"Piovera - Conde Orgaz, Hortaleza, Madrid",1.795.000 €,4.0,5.0,291 m²,"['Aire acondicionado', 'Amueblado', 'Armarios ...","['Aire acondicionado: otros', 'Año de construc...","['Consumo', 'Emisiones', 'a']",Se vende fantastica vivienda arrendada con inq...,03/03/2023

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9996 entries, 0 to 9995
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              9996 non-null   int64
 1   Títulos                 9972 non-null   object
 2   Ubicaciones             9972 non-null   object
 3   Precios                 9972 non-null   object
 4   Número de habitaciones  9798 non-null   float64
 5   Número de baños         9972 non-null   float64
 6   Medidas                 9972 non-null   object
 7   Equipamientos           9957 non-null   object
 8   Características         9972 non-null   object
 9   Consumo energético      5615 non-null   object
 10  Descripciones           9971 non-null   object
 11  Fechas de publicación   9972 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 937.3+ KB

In [5]:
df = total_eda(df)

c:\Users\ruben\OneDrive\Documentos\Bootcamp\Apuntes Bootcamp\Librerías\Proyecto Final\Proyecto\Funciones_Datos_EDA.py:17: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  viviendas['Equipamientos'] = viviendas['Equipamientos'].str.replace('[', '').str.replace(']', '')
c:\Users\ruben\OneDrive\Documentos\Bootcamp\Apuntes Bootcamp\Librerías\Proyecto Final\Proyecto\Funciones_Datos_EDA.py:19: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  viviendas['Características'] = viviendas['Características'].str.replace('[', '').str.replace(']', '')
c:\Users\ruben\OneDrive\Documentos\Bootcamp\Apuntes Bootcamp\Librerías\Proyecto Final\Proyecto\Funciones_Datos_EDA.py:21: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  viviendas['Consumo energético'] = viviendas['Consumo energético'].str.replace('[', '').str.replace(']', '')
c:\Users\ruben\OneDrive\Documentos\Bootcamp\Apuntes Bootcamp\Librerías\Proyecto Final\Proyecto\Funciones_Datos_EDA.py:143: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  viviendas['Precio'] = pd.to_numeric(viviendas['Precio'].str.replace('.', ''), errors='coerce').astype('Int64')
c:\Users\ruben\OneDrive\Documentos\Bootcamp\Apuntes Bootcamp\Librerías\Proyecto Final\Proyecto\Funciones_Datos_EDA.py:146: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  viviendas['Superficie'] = pd.to_numeric(viviendas['Superficie'].astype(str).str.replace('.', ''), errors='coerce').astype('Int64')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7465 entries, 0 to 7464
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Distrito                 7456 non-null   object
 1   Barrio                   7453 non-null   object
 2   Precio                   7465 non-null   Int64
 3   Habitaciones             7332 non-null   Int64
 4   Baños                    7465 non-null   Int64
 5   Superficie               7465 non-null   Int64
 6   Aire acondicionado       7465 non-null   bool
 7   Amueblado                7465 non-null   bool
 8   Armarios empotrados      7465 non-null   bool
 9   Ascensor                 7465 non-null   bool
 10  Balcón                   7465 non-null   bool
 11  Calefacción              7465 non-null   bool
 12  Garaje                   7465 non-null   bool
 13  Jardín                   7465 non-null   bool
 14  Piscina                  7465 non-null   bool
 15  Terraza                  7465 non-null   bool
 16  Año de construcción      5200 non-null   float64
 17  Planta                   6431 non-null   float64
 18  Estado                   7465 non-null   object
 19  Interior/Exterior        6630 non-null   object
 20  Tipo de calefacción      4245 non-null   object
 21  Sistema de calefacción   6402 non-null   object
 22  Calificación energética  4163 non-null   object
dtypes: Int64(4), bool(10), float64(2), object(7)
memory usage: 860.4+ KB

In [7]:
df.isnull().sum()

Distrito                      9
Barrio                       12
Precio                        0
Habitaciones                133
Baños                         0
Superficie                    0
Aire acondicionado            0
Amueblado                     0
Armarios empotrados           0
Ascensor                      0
Balcón                        0
Calefacción                   0
Garaje                        0
Jardín                        0
Piscina                       0
Terraza                       0
Año de construcción        2265
Planta                     1034
Estado                        0
Interior/Exterior           835
Tipo de calefacción        3220
Sistema de calefacción     1063
Calificación energética    3302
dtype: int64

In [8]:
df.head()

,Distrito,Barrio,Precio,Habitaciones,Baños,Superficie,Aire acondicionado,Amueblado,Armarios empotrados,Ascensor,Balcón,Calefacción,Garaje,Jardín,Piscina,Terraza,Año de construcción,Planta,Estado,Interior/Exterior,Tipo de calefacción,Sistema de calefacción,Calificación energética
0,Retiro,Pacífico,565000,5,2,160,False,False,True,True,True,True,False,False,False,True,NaN,3.0,Por reformar,Exterior,Gas Natural,Central,E
1,Centro,Justicia - Chueca,299990,1,1,84,False,False,False,False,False,False,False,False,False,False,NaN,NaN,Buen estado,Interior,NaN,NaN,NaN
2,Centro,Embajadores - Lavapiés,179000,1,1,57,False,False,False,False,False,False,False,False,False,False,NaN,NaN,Buen estado,Interior,NaN,NaN,NaN
3,Hortaleza,Canillas,1875000,4,5,346,True,False,True,True,False,True,True,True,True,True,2020.0,3.0,Buen estado,Exterior,Electricidad,Independiente,A
4,Hortaleza,Piovera - Conde Orgaz,1795000,4,5,291,True,True,True,True,False,True,True,False,True,True,2018.0,1.0,Buen estado,Exterior,NaN,Independiente,A

In [9]:
# df.to_pickle('viviendas_eda2.pkl')
# df.to_csv('viviendas_eda2.csv', index=True)